### ISSUE TITLE
Never finishes initizalization on UC Browser

### ISSUE THREAD

**Issue by NOtherDev** [tomayac/pwa-feature-detector#1]
It stays on the "Detecting Progressive Web App features…" screen forever.
I guess it is due to unhandled exception caused by [missing `relList` support](https://caniuse.com/#feat=rellist). But I have no idea how to debug it properly.

**Comment by toxic-johann** [comment]
Maybe you can use UC developer edition on [https://plus.ucweb.com/download/](https://plus.ucweb.com/download/) ？

And you can follow the advice on [How to debug pages in UC browser](https://plus.ucweb.com/docs/pwa/docs-en/nlhd5r).

By the way, @NOtherDev can you tell me the version of your UC Browser. UC Browser doesn't support PWA well until UC 12.0.

**Comment by NOtherDev** [comment]
@toxic-johann it's 11.5.0.1015 indeed. I'll check the Developer Edition, thanks!

**Comment by NOtherDev** [comment]
@toxic-johann I'm unable to find download link for 12.0, there is 11.5 everywhere – at least for the "international" edition. Nevertheless their status pages seem to indicate proper PWA support on 11.5 that is based on Chromium 57.

Anyway, thanks for the insight and debugging tips. One of the pwa-feature-detector's issue is indeed missing `relList` support. But it's more than that - it seems arrow functions are not there yet:

![image](https://user-images.githubusercontent.com/1309057/35063988-ec0878e4-fbc8-11e7-92ab-bd4feaf98636.png)

**Comment by toxic-johann** [comment]
@NOtherDev Hmmm. The most popular version of international UC Browser now is 11.5. 11.8 is under publishing. There is still some time away from full PWA support. I will tell you back once I found out the latest version.

**Comment by tomayac** [comment]
I reckon this is suboptimal, but as the tool is targeted at Web browsers and Web Views that have at least basic PWA support, I don't think supporting browsers that don't even know fat arrow functions yet makes a lot of sense. 

FWIW, I have installed the latest version of UC Browser (v12.0.0.1088) on my phone, but it doesn't load a single page and there is no way to turn off data saving mode (which I suspect is causing the issue). I'm inclined to drop the mic here.
